const labelList = [
  {
    title: "饮食",
    labels: [
      "canyin",
      "mifan",
      "haixian",
      "huoguo",
      "hanbao",
      "jitui",
      "shaokao",
      "maicai",
      "shuiguo",
      "xiangjiao",
      "pingguo",
      "jiushui",
      "bingjiling",
      "lingshi",
      "dangao",
    ],
  },
  {
    title: "娱乐",
    labels: [
      "yule",
      "youxi",
      "yumaoqiu",
      "lanqiu",
      "wangqiu",
      "baxin",
      "puke",
      "lunhua",
      "dianshi",
      "huaxue",
      "baoling",
      "youleyuan",
    ],
  },
  {
    title: "购物",
    labels: ["gouwu", "riyong", "fushi", "huazhuang", "gaogen", "xie", "liwu"],
  },
  {
    title: "学习",
    labels: ["xuexiao", "xuexi", "jita", "wenjv", "shu", "hua", "jisuanqi"],
  },
  {
    title: "医疗",
    labels: [
      "yisheng",
      "diandi",
      "dazhen",
      "tingzhen",
      "yaoxiang",
      "yao",
      "ya",
      "yun",
      "CT",
    ],
  },
  {
    title: "交通",
    labels: [
      "jiaotong",
      "danche",
      "feiji",
      "didi",
      "motuo",
      "jiayou",
      "gaotie",
      "che",
    ],
  },
];

export default labelList;
